spring:
  threads:
    virtual:
      enabled: true
  graphql:
    graphiql:
      enabled: true
  messages:
    basename: messages/messages
    encoding: UTF-8
  docker:
    compose:
      file: src/main/resources/compose.yml
  data:
    mongodb:
      database: test
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256
demo:
  shared.secret: b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86
  issuer:
    url: https://auth.example.com
mongock:
  enabled: true
  runner-type: applicationrunner
  transaction-enabled: true
  migration-scan-package: com.example.graph.migration
