# IntelliI Config file
projects:
  demo:
    schema: .local.graphql
    documents: '**/*.graphql'
    extensions:
      endpoints:
        Local:
          url: http://localhost:8080/graphql
          headers:
            Authorization: bearer ${TOKEN}
